import { motion } from 'framer-motion'
import { ArrowDownRight, CheckCircle2, ChevronRight, FileCheck2, MoreHorizontal, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button, Reveal, SectionHeading, TextLink } from '../components/Shared'
import { caseStudies, coffeeFlow, credibility, dashboardStats, industries, problems, processSteps, services, whyUs } from '../data/site'

function DashboardPreview() {
  return <motion.div initial={{ opacity: 0, scale: .94, y: 30 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: .8, delay: .2 }} className="relative mx-auto max-w-[640px] lg:ml-auto">
    <div className="absolute -inset-8 rounded-full bg-cyan/10 blur-3xl" />
    <div className="relative overflow-hidden rounded-[28px] border border-white/10 bg-panel shadow-2xl shadow-cyan/10 dashboard-noise">
      <div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-red-400/80"/><span className="h-2.5 w-2.5 rounded-full bg-amber-300/80"/><span className="h-2.5 w-2.5 rounded-full bg-success/80"/></div><div className="rounded-lg bg-white/5 px-3 py-1 text-[10px] uppercase tracking-[.2em] text-slate-400">Operations overview</div><MoreHorizontal size={18} className="text-slate-500" /></div>
      <div className="grid min-h-[430px] grid-cols-[82px_1fr]">
        <div className="border-r border-white/10 p-3"><div className="mb-6 grid h-10 w-10 place-items-center rounded-xl bg-cyan text-xs font-extrabold text-ink">ERP</div>{[0,1,2,3,4,5].map((item) => <div key={item} className={`mb-3 h-10 rounded-xl ${item===0?'bg-cyan/15 border border-cyan/25':'bg-white/[.035]'}`} />)}</div>
        <div className="p-4 sm:p-5">
          <div className="mb-5 flex items-start justify-between"><div><p className="text-xs text-slate-500">Saturday, 18 July</p><h3 className="mt-1 font-display text-lg font-bold text-white">Business operations</h3></div><div className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-brand to-cyan text-xs font-bold">AM</div></div>
          <div className="grid gap-3 sm:grid-cols-3">{dashboardStats.map(({label,value,icon:Icon}) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.045] p-3"><Icon size={17} className="text-cyan"/><p className="mt-4 text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-sm font-bold text-white">{value}</p></div>)}</div>
          <div className="mt-3 grid gap-3 sm:grid-cols-[1.4fr_.8fr]">
            <div className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider text-slate-500">Monthly activity</p><p className="mt-1 text-sm font-bold text-white">Records by workflow</p></div><TrendingUp size={17} className="text-success" /></div><div className="mt-7 flex h-28 items-end gap-2">{[38,58,46,74,64,88,72,96,82].map((h,i)=><span key={i} className="flex-1 rounded-t-md bg-gradient-to-t from-brand/40 to-cyan" style={{height:`${h}%`}} />)}</div></div>
            <div className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">Approvals</p><div className="mt-4 space-y-3">{['Purchase record','Stock issue','Export document'].map((x,i)=><div key={x} className="flex items-center gap-2 rounded-xl bg-black/10 p-2"><span className={`h-2 w-2 rounded-full ${i===1?'bg-amber-300':'bg-success'}`} /><span className="text-[10px] text-slate-300">{x}</span></div>)}</div></div>
          </div>
          <div className="mt-3 flex items-center justify-between rounded-2xl border border-cyan/15 bg-cyan/[.06] p-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-cyan/15 text-cyan"><FileCheck2 size={18}/></div><div><p className="text-xs font-bold text-white">Document generation</p><p className="text-[10px] text-slate-500">Controlled exports and templates</p></div></div><ChevronRight size={17} className="text-cyan" /></div>
        </div>
      </div>
    </div>
    <div className="absolute -bottom-5 -left-4 hidden rounded-2xl border border-white/10 bg-panel2 p-4 shadow-xl sm:block"><p className="text-[10px] uppercase tracking-[.15em] text-slate-500">System principle</p><p className="mt-1 text-sm font-bold text-white">One source of truth</p></div>
  </motion.div>
}

export default function HomePage() {
  return <>
    <section className="relative overflow-hidden bg-ink pb-24 pt-40 text-white dark-grid hero-glow lg:pb-28 lg:pt-44"><div className="container-shell relative z-10 grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}><span className="eyebrow">ERP • Automation • Web Platforms</span><h1 className="display-title mt-6">Run your business with <span className="text-cyan">one reliable</span> digital system.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">We build custom ERP systems, business applications and professional websites for Ethiopian companies—designed around your workflows, documents, teams and reporting needs.</p><div className="mt-8 flex flex-wrap gap-3"><Button to="/contact">Book a Workflow Assessment</Button><Button to="/services" variant="secondary">Explore Our Services</Button></div><div className="mt-8 flex items-center gap-3 text-xs text-slate-400"><CheckCircle2 size={16} className="text-success" /> No invented packages. Every system begins with an operational assessment.</div></motion.div><DashboardPreview /></div></section>

    <section className="border-b border-slate-200 bg-white"><div className="container-shell grid grid-cols-2 gap-px py-6 sm:grid-cols-3 lg:grid-cols-6">{credibility.map(item=><div key={item} className="px-3 py-3 text-center text-xs font-bold text-slate-600">{item}</div>)}</div></section>

    <section className="section-pad"><div className="container-shell"><SectionHeading eyebrow="Operational challenges" title="Is your business still controlled through spreadsheets, paper records and scattered messages?" text="A digital system should improve visibility and accountability—not simply reproduce manual work on a screen." /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{problems.map((item,i)=><Reveal key={item} delay={i*.05}><div className="card group flex min-h-36 items-start justify-between p-6 transition hover:-translate-y-1 hover:border-cyan/40 hover:shadow-soft"><div><span className="text-xs font-extrabold text-cyan">0{i+1}</span><h3 className="mt-4 max-w-xs font-display text-lg font-bold leading-7 text-slate-950">{item}</h3></div><ArrowDownRight className="text-slate-300 transition group-hover:text-cyan" /></div></Reveal>)}</div></div></section>

    <section className="section-pad bg-white"><div className="container-shell"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><SectionHeading eyebrow="What we build" title="Focused digital systems for real operational work." text="The homepage prioritises the services most relevant to business control, stock, documents, customer management and reporting." /><TextLink to="/services">View all services</TextLink></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.slice(0,6).map(({icon:Icon,title,text,number},i)=><Reveal key={title} delay={i*.04}><Link to="/services" className="card group block h-full p-6 transition hover:-translate-y-1 hover:border-cyan/40 hover:shadow-soft"><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-ink text-cyan"><Icon size={23}/></div><span className="font-display text-sm font-extrabold text-slate-300">{number}</span></div><h3 className="mt-6 font-display text-xl font-bold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p><span className="mt-6 inline-flex items-center gap-1 text-sm font-bold text-cyan">Learn more <ChevronRight size={16}/></span></Link></Reveal>)}</div></div></section>

    <section className="section-pad relative overflow-hidden bg-ink text-white dark-grid"><div className="container-shell relative z-10 grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><Reveal><SectionHeading eyebrow="Flagship solution" title="Coffee-export operations, connected from purchase to reporting." text="A specialised ERP structure designed around the records, stock movements, documents and controls used by coffee exporters." dark /><div className="mt-8 flex flex-wrap gap-3"><Button to="/coffee-erp">Explore Coffee ERP</Button><Button to="/contact" variant="secondary">Request a Demonstration</Button></div></Reveal><Reveal delay={.1}><div className="rounded-[28px] border border-white/10 bg-panel p-5 shadow-glow"><div className="grid gap-3 sm:grid-cols-2">{coffeeFlow.map((step,i)=><div key={step} className={`relative rounded-2xl border p-4 ${i===coffeeFlow.length-1?'border-cyan/30 bg-cyan/10':'border-white/10 bg-white/[.04]'}`}><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Step {String(i+1).padStart(2,'0')}</p><p className="mt-2 font-display text-sm font-bold text-white">{step}</p>{i<coffeeFlow.length-1 && <ChevronRight className="absolute -right-2 top-1/2 hidden -translate-y-1/2 text-cyan sm:block" size={16}/>}</div>)}</div></div></Reveal></div></section>

    <section className="section-pad"><div className="container-shell"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><SectionHeading eyebrow="Industries" title="Industry knowledge makes custom software more practical." text="Start with sectors where we understand the operational language, documents and reporting expectations." /><TextLink to="/industries">Explore industries</TextLink></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{industries.slice(0,8).map(({icon:Icon,title,text},i)=><Reveal key={title} delay={i*.035}><div className="card h-full p-5"><Icon className="text-cyan" size={22}/><h3 className="mt-5 font-display font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div></Reveal>)}</div></div></section>

    <section className="section-pad bg-white"><div className="container-shell"><SectionHeading eyebrow="Why work with us" title="A focused partner, not a distant software factory." text="The website presents a realistic founder-led delivery model with direct communication and documented responsibilities." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{whyUs.map(({icon:Icon,title,text},i)=><Reveal key={title} delay={i*.04}><div className="rounded-2xl border border-slate-200 bg-paper p-6"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white text-cyan shadow-sm"><Icon size={21}/></div><h3 className="mt-5 font-display text-lg font-bold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></div></Reveal>)}</div></div></section>

    <section className="section-pad"><div className="container-shell"><SectionHeading eyebrow="Delivery process" title="A controlled path from business problem to working system." text="Each stage produces decisions and evidence before the project moves forward." /><div className="mt-12 grid gap-4 lg:grid-cols-7">{processSteps.map((step,i)=><Reveal key={step.number} delay={i*.04}><div className="relative h-full rounded-2xl border border-slate-200 bg-white p-5"><span className="font-display text-xl font-extrabold text-cyan">{step.number}</span><h3 className="mt-5 font-display font-bold text-slate-950">{step.title}</h3><p className="mt-3 text-xs leading-6 text-slate-600">{step.text}</p>{i<processSteps.length-1 && <span className="absolute -right-2 top-8 hidden h-px w-4 bg-cyan lg:block"/>}</div></Reveal>)}</div><div className="mt-8"><TextLink to="/process">See the complete implementation approach</TextLink></div></div></section>

    <section className="section-pad bg-ink text-white dark-grid"><div className="container-shell"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><SectionHeading eyebrow="Selected work" title="Show the problem, the workflow and the current project status." text="No invented clients or results. Every project is labelled honestly as a live system, working demo, prototype or service capability." dark /><TextLink to="/work">View all work</TextLink></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{caseStudies.slice(0,3).map(({icon:Icon,category,title,status,problem,modules},i)=><Reveal key={title} delay={i*.05}><div className="h-full rounded-2xl border border-white/10 bg-white/[.045] p-6"><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan/10 text-cyan"><Icon/></div><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-slate-300">{status}</span></div><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-cyan">{category}</p><h3 className="mt-2 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{problem}</p><div className="mt-5 flex flex-wrap gap-2">{modules.slice(0,4).map(x=><span key={x} className="rounded-lg bg-white/5 px-2.5 py-1.5 text-[10px] text-slate-300">{x}</span>)}</div></div></Reveal>)}</div></div></section>

    <section className="section-pad bg-white"><div className="container-shell grid gap-12 lg:grid-cols-[1fr_.9fr] lg:items-center"><Reveal><SectionHeading eyebrow="Start with the workflow" title="Ready to replace manual work with a reliable business system?" text="Tell us how your company currently operates. We will help identify the right system, modules and implementation approach." /><div className="mt-8 flex flex-wrap gap-3"><Button to="/contact">Book a Free Consultation</Button><Button to="/faq" variant="light">Read Common Questions</Button></div></Reveal><Reveal delay={.1}><div className="rounded-[28px] border border-slate-200 bg-paper p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan">First discussion</p><h3 className="mt-3 font-display text-2xl font-bold text-slate-950">Bring your current process—not a technical specification.</h3><ul className="mt-6 space-y-4">{['The spreadsheets, forms or documents you currently use','The roles involved in each step','The reports management needs','The problems that cause delay or errors'].map(x=><li key={x} className="flex gap-3 text-sm leading-6 text-slate-600"><CheckCircle2 size={18} className="mt-1 shrink-0 text-success"/>{x}</li>)}</ul></div></Reveal></div></section>
  </>
}
